# Generated by Django 5.2.9 on 2025-12-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fav_genres',
            field=models.ManyToManyField(blank=True, to='tracks.genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
