# Generated by Django 5.2.9 on 2025-12-18 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('followers', models.ManyToManyField(blank=True, related_name='following_artists', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(blank=True, to='tracks.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.TextField()),
                ('track_id', models.TextField()),
                ('track_popularity', models.IntegerField()),
                ('artist_name', models.TextField()),
                ('artist_id', models.TextField()),
                ('release_year', models.DateField()),
                ('duration_ms', models.IntegerField()),
                ('track_image_link', models.URLField()),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_tracks', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(blank=True, to='tracks.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
                ('tracks', models.ManyToManyField(blank=True, related_name='playlists', to='tracks.track')),
            ],
        ),
    ]
