# Generated by Django 5.2.9 on 2025-12-23 02:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('artist_id', models.TextField()),
                ('followers', models.ManyToManyField(blank=True, related_name='following_artists', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(blank=True, to='tracks.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.TextField()),
                ('track_id', models.TextField()),
                ('release_date_text', models.CharField(blank=True, max_length=10, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('track_image_link', models.URLField()),
                ('artist', models.ManyToManyField(blank=True, to='tracks.artist')),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_tracks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
