# Generated by Django 5.2.9 on 2025-12-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='release_date_text',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
