# Generated by Django 5.2.9 on 2025-12-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='video_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
