# Generated by Django 5.2.9 on 2025-12-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_release_date_text_alter_track_release_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist_id',
        ),
        migrations.RemoveField(
            model_name='track',
            name='genre',
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(blank=True, to='tracks.artist'),
        ),
    ]
