# Generated by Django 5.2.9 on 2025-12-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_video_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
